select * from v$version;
show parameter job_que;
show parameter streams_pool_size;
show parameter sga_targ;
show parameter memory_targ;
show parameter java_pool;
alter system set streams_pool_size=512m;
show parameter java_pool;
alter system set java_pool_size=512m;
show parameter undo_ret;
alter system set undo_retention=3600;
show parameter streams_pool;
show parameter java_pool;
show parameter undo_re;
archive log list;
shutdown immediate;
startup mount;
alter database archivelog;
alter database force logging;
alter database add supplemental log data;  
alter database open;